OmniCar/SAM-types

- types/contractProvider.d.ts
These features requires this extension
https://github.com/OmniCar/SAM-api/issues/1633
https://github.com/OmniCar/SAM-superadmin-frontend/issues/320
> This is to be merged when the corresponding feature is done

- types/contract/contractDetails.d.ts
- types/contractAction.d.ts
But you get to deploy it though :-)
> Made seller property on IContractDetailsRecord optional

- types/workshopOperation.d.ts
* added string as an optional type for date in workshopoperation
> added string as an optional type for date in workshopoperation

- types/contract/contractList.d.ts
- types/queryParams.d.ts
* Make all pagination data optional
> Add health to IContractListRecord

- types/admin/vehicle/vehicle.d.ts
* Make paymentGateway and reference optional instead of using null
> Add activationUrl to IApiVehicleContract

- types/admin/contract/index.d.ts
- types/admin/contract/templateLookup.d.ts
- types/admin/contract/vehicleLookup.d.ts
* vehicleLookup.d.ts -> templateLookup.d.ts
* renamed firstRegistrationDate -> regDate
> Renamed vehicleLookup to templateLookup and also a property name

- types/admin/contractCreation/contractCreation.d.ts
@IgorJoergensen This is pretty much what we agreed on the other day. Let me know if this is ok.
> Contract adjustment response

- types/admin/contractCreation/contractCreation.d.ts
> Change providerShare to PriceSpecification

- types/admin/vehicle/vehicle.d.ts
- types/contract/contractList.d.ts
- types/contract/contractQuery.d.ts
part of https://app.zenhub.com/workspaces/sam-et-al-5a0969d4c91bb13bb65fa6c0/issues/omnicar/sam-admin-v2/808
> Order by contract creation date

- types/admin/chart/contractCharts.d.ts
- types/admin/chart/index.d.ts
- types/admin/index.d.ts
- types/chart.d.ts
@olefrank I changed the type according to our talk with Rasmus. Just doing the economy chart for now. The mileage types we'll do as a separate PR later.
> Add types for economy chart

- types/index.ts
Remove const status of all common enums (throughout errors with react-scripts-ts 3.1)
> Remove const status of all common enums

- types/contractTemplate.d.ts
This branch was used to create v0.0.248 release
> Added default mileage and duration to contract templates

- types/admin/contractProvider/index.d.ts
New interface for creating test/demo providers
> New interface for creating test/demo providers

- types/admin/contractProvider/index.d.ts
> autoexperten progress

- types/contract/contractFilter.d.ts
https://fragus-it.monday.com/boards/467282465/pulses/1078248552
pull request in sam-types, admin and api
> see how many contracts that exist with each status

- types/admin/contractCreation/contractCreation.d.ts
- types/contract/contractOffer.d.ts
- types/vehicle.d.ts
* Added engine power (kW) param to vehicle
* Added interface vehicle lookup response
* Added vehicle type
> Feature - kW in vehicle and contracts

- types/admin/contractCreation/contractCreation.d.ts
- types/contractTemplate.d.ts
to IContractTemplateResponse and ICommonContractUpdateRequest
> Add serviceVarantId and serviceVariantName

- types/responseErrors/workshopResponseErrors.d.ts
Added new errors;
- Too many records
- Invalid column count
- Invalid header
> Added more errrors to WorkshopImportErrors

- types/admin/contract/basicInfo.d.ts
- types/admin/contract/contractDetails.d.ts
Related to:
https://fragus-it.monday.com/boards/1372693523/pulses/3165926506
> added extendedTo/adjustedTo property to contract

- types/admin/contract/basicInfo.d.ts
Added optional offer expiration date prop to IBasicContractInfo
> Added optional offer expiration date prop to IBasicContractInfo

- types/vehicle.d.ts
Added original arg since engineMaxPower can be overriden
> Feature - Added original arg since engineMaxPower can be overriden

- types/v4PricingTool/productsAndContracts/index.ts
Reverts OmniCar/SAM-types#543
Messes up things, I'll fix it another way
> Revert "Added payment type request by Johan W"

- README.md
> Updated README.md description
